name: Release

on: 
  push:
    tags:
      - '!player/'
      - 'v*'

jobs:
  ci:
    steps:
      - uses: bitmovin/bitmovin-player-ui/.github/workflows/ci.yml@feature/github-actions

  download_artifact:
    needs: ci

    uses: actions/download-artifact@v3
    with:
      path: .

  publish:
    needs: download_artifact
    runs-on: ubuntu-latest

    steps:
      - name: Publish
        run: ./publish.sh
        shell: bash
        env:
          NPM_DRY_RUN: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
