name: Release

on: 
  push:
    tags:
      - '!player/'
      - 'v*'

jobs:
  test_and_build:
    uses: ./.github/workflows/ci.yml

  download_and_publish:
    needs: test_and_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Extract version from tag
        uses: actions/github-script@v6
        id: extract-version
        with:
          script: |
            const { getPlayerUiVersion } = require('./.github/scripts/defineVersion.js')
            return getPlayerUiVersion("${{ github.ref }}")

      - uses: actions/download-artifact@v3
        with:
          path: .

      - name: Unpackage artifact files
        run: tar -xzvf artifact/artifact.tar.gz -C .
        shell: bash

      - name: Publish
        run: ./publish.sh
        shell: bash
        env:
          NPM_DRY_RUN: false
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Upload API Docs
        uses: ./.github/actions/publish-docs
        with:
          docs_path: './docs/'
          destination_path: "player/ui/${{ fromJson(steps.extract-version.outputs.result).full }}/"
          bucket: ${{ secrets.GCS_BUCKET }}
          credentials_json: ${{ secrets.GCS_CREDENTIALS }}

      - name: Upload API Docs for major version
        uses: ./.github/actions/publish-docs
        with:
          docs_path: './docs/'
          destination_path: 'player/ui/3/'
          bucket: ${{ secrets.GCS_BUCKET }}
          credentials_json: ${{ secrets.GCS_CREDENTIALS }}

      - name: Notify team
        run: node .github/scripts/notifySlackTeam.js 'success' 'CHANGELOG.md' ${{ secrets.RELEASE_SUCCESS_SLACK_WEBHOOK }}

  handle_failure:
    runs-on: ubuntu-latest
    needs: [test_and_build, download_and_publish]
    if: ${{ always() && (needs.download_and_publish.result == 'failure' || needs.test_and_build.result == 'failure') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Notify team
        run: node .github/scripts/notifySlackTeam.js 'failure' 'CHANGELOG.md' ${{ secrets.RELEASE_FAILURE_SLACK_WEBHOOK }} ${{ github.run_id }}
