name: Release

on: 
  push:
    tags:
      - '!player/'
      - 'v*'

jobs:
  ci:
    uses: .github/workflows/ci.yml@feature/github-actions

  download_artifact:
    uses: actions/download-artifact@v3
    with:
      path: .
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish
        run: ./publish.sh
        shell: bash
        env:
          NPM_DRY_RUN: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
