name: Release

on: 
  push:
    tags:
      - '!player/'
      - 'v*'

jobs:
  test_and_build:
    uses: ./.github/workflows/ci.yml

  download_artifact:
    needs: test_and_build

    uses: actions/download-artifact@v3
    with:
      path: .

  publish:
    needs: download_artifact
    runs-on: ubuntu-latest

    steps:
      - name: Publish
        run: ./publish.sh
        shell: bash
        env:
          NPM_DRY_RUN: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
